#!/usr/bin/env python3
"""Cut the Material Symbols icon font down to the icons SmartChef actually uses.

The npm package ships one variable font carrying all ~4,300 icons: 3.96 MB,
declared `font-display: block`, and referenced by essentially every screen.
So every cold start — web, PWA, Electron and the APK alike — rendered a UI
with no icons at all until four megabytes had finished arriving. The app
uses about 350 of those icons.

Subsetting an icon font is not the usual "keep these characters" job. Icons
are reached by *ligature*: the markup says `<span
class="material-symbols-outlined">restaurant</span>` and the font rewrites
the letters r-e-s-t-a-u-r-a-n-t into one glyph. Keeping the letters a-z
therefore keeps every ligature that can be built from them — that is, all
of them, and no saving at all. What actually works is to ask for the
ligature *output* glyphs by name and pass --no-layout-closure, so the
subsetter prunes every ligature whose result is gone.

Which icons are in use is read out of the source rather than maintained by
hand, so adding one is just writing it in the JSX. The scan is deliberately
generous: any lowercase word anywhere in src/ that happens to be a real
icon name is kept, which covers icon names held in constant tables and read
back through `{opt.icon}` as well as ones written inline. A few extra
glyphs cost a few KB; a missing one renders as the literal word, so the
error is worth making in this direction.

Run it with `npm run icons:subset`. The build runs it too (see the
`prebuild` script), and falls back to the committed output if Python or
fontTools is missing, so a machine without them can still build — it just
cannot pick up newly added icons. src/fonts/icons.txt lists what the
committed font covers, and iconCoverage.test.ts fails if the source has
outgrown it.
"""

import glob
import os
import re
import subprocess
import sys

FRONTEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_FONT = os.path.join(FRONTEND, 'node_modules', 'material-symbols', 'material-symbols-outlined.woff2')
OUT_DIR = os.path.join(FRONTEND, 'src', 'fonts')
OUT_FONT = os.path.join(OUT_DIR, 'material-symbols-outlined-subset.woff2')
OUT_CSS = os.path.join(OUT_DIR, 'material-symbols.css')
OUT_LIST = os.path.join(OUT_DIR, 'icons.txt')

CSS_TEMPLATE = """/* GENERATED by scripts/subset-material-symbols.py — do not edit.
   Regenerate with `npm run icons:subset`.
   {count} icons, {size_kb} KB, down from the package's 3868 KB. */
@font-face {{
  font-family: "Material Symbols Outlined";
  font-style: normal;
  font-weight: 100 700;
  font-display: block;
  src: url("./material-symbols-outlined-subset.woff2") format("woff2");
}}
.material-symbols-outlined {{
  font-family: "Material Symbols Outlined";
  font-weight: normal;
  font-style: normal;
  font-size: 24px;
  line-height: 1;
  letter-spacing: normal;
  text-transform: none;
  display: inline-block;
  white-space: nowrap;
  word-wrap: normal;
  direction: ltr;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-rendering: optimizeLegibility;
  font-feature-settings: "liga";
}}
"""


def ligature_names(font):
    """Every icon name the font can render, mapped to the glyph it produces.

    The letter glyphs are mapped from both the upper- and lower-case
    codepoints, and the reverse lookup below takes whichever comes first —
    so names come back as "ADD" and are lowercased to match the markup.
    """
    reverse = {}
    for codepoint, glyph in font.getBestCmap().items():
        reverse.setdefault(glyph, chr(codepoint))

    def subtables(lookup):
        for sub in lookup.SubTable:
            # Big fonts wrap their lookups in extension subtables to get
            # past the 16-bit offsets in GSUB.
            yield sub.ExtSubTable if sub.__class__.__name__ == 'ExtensionSubst' else sub

    names = {}
    for lookup in font['GSUB'].table.LookupList.Lookup:
        for sub in subtables(lookup):
            if sub.__class__.__name__ != 'LigatureSubst':
                continue
            for first, ligatures in sub.ligatures.items():
                head = reverse.get(first)
                if head is None:
                    continue
                for ligature in ligatures:
                    tail = ''.join(reverse.get(g, '') for g in ligature.Component)
                    if len(tail) != len(ligature.Component):
                        continue
                    names[(head + tail).lower()] = ligature.LigGlyph
    return names


def icons_used_in_source(known):
    text = []
    for pattern in ('src/**/*.tsx', 'src/**/*.ts'):
        for path in glob.glob(os.path.join(FRONTEND, pattern), recursive=True):
            with open(path, encoding='utf-8') as handle:
                text.append(handle.read())
    tokens = set(re.findall(r'[a-z][a-z0-9_]{1,40}', '\n'.join(text)))
    return sorted(tokens & set(known))


def main():
    from fontTools.ttLib import TTFont

    font = TTFont(SOURCE_FONT)
    known = ligature_names(font)
    used = icons_used_in_source(known)
    if not used:
        sys.exit('found no icon names in src/ — refusing to write an empty font')

    glyphs = sorted({known[name] for name in used})
    characters = ''.join(sorted(set(''.join(used))))

    os.makedirs(OUT_DIR, exist_ok=True)
    subprocess.run(
        [sys.executable, '-m', 'fontTools.subset', SOURCE_FONT,
         '--output-file=' + OUT_FONT,
         '--flavor=woff2',
         # The ligature results, by glyph name...
         '--glyphs=' + ','.join(glyphs),
         # ...and the letters those ligatures are spelled with, so the
         # substitution still has inputs to match.
         '--text=' + characters,
         '--layout-features=liga,dlig,rlig,ccmp,calt',
         # Without this the subsetter follows GSUB from a-z and drags every
         # icon back in — see the module docstring.
         '--no-layout-closure',
         '--name-IDs=*',
         '--notdef-outline'],
        check=True,
    )

    verify(used)

    size = os.path.getsize(OUT_FONT)
    with open(OUT_CSS, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(CSS_TEMPLATE.format(count=len(used), size_kb=size // 1024))
    with open(OUT_LIST, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write('\n'.join(used) + '\n')

    print(f'material-symbols: {len(used)} icons, {size // 1024} KB '
          f'(was {os.path.getsize(SOURCE_FONT) // 1024} KB)')


def verify(used):
    """Re-read the subset and confirm every icon still resolves.

    A subsetter flag that quietly stops working would otherwise ship a font
    whose icons render as their own names, which is exactly the failure this
    script must never cause.
    """
    from fontTools.ttLib import TTFont

    missing = sorted(set(used) - set(ligature_names(TTFont(OUT_FONT))))
    if missing:
        os.remove(OUT_FONT)
        sys.exit(f'subset lost {len(missing)} icons, e.g. {missing[:5]} — not writing it')


if __name__ == '__main__':
    main()
