require('./rt/electron-rt');
//////////////////////////////
// User Defined Preload scripts below

// SmartChef: a small, independent IPC bridge for the folder-sync feature's
// native "choose a folder" dialog — kept separate from the auto-generated
// Capacitor plugin bridge above (rt/electron-rt.ts, regenerated by `cap
// sync`) so it survives that regeneration untouched. Renderer side:
// frontend/src/lib/electronBridge.ts.
// contextIsolation is on (see electron/src/setup.ts), so the renderer
// (our React app) can't `require('fs')` directly even with nodeIntegration
// enabled — every filesystem primitive gitfs.ts needs is bridged through
// IPC to the main process (which has real Node/OS access), the same way
// pickSyncFolder is. Binary data (git objects) crosses as Uint8Array
// directly — Electron's IPC structured-clones it, no base64 needed (unlike
// the Capacitor plugin bridge's JSON-only channel used on mobile).
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('smartchefElectron', {
  pickSyncFolder: () => ipcRenderer.invoke('smartchef-pick-sync-folder'),
  // Native save dialog for the encrypted Setup File — see the
  // `smartchef-save-file` handler in electron/src/index.ts for why the
  // renderer's own blob-download trick isn't used here.
  saveFile: (suggestedName: string, contents: string) =>
    ipcRenderer.invoke('smartchef-save-file', suggestedName, contents),
  // Local Storage (wayfinder ticket 03/05, standalone-storage-sync map) —
  // distinct from the sync folder above: this is where the live SQLite db
  // and content-addressed images actually live, not the (future) Hidden
  // Clone/Sync Folder.
  getLocalStorageDir: () => ipcRenderer.invoke('smartchef-get-local-storage-dir'),
  // Hidden Clone (wayfinder ticket 03 remainder) — each device's own
  // private git working copy, distinct from both Local Storage above and
  // the user-chosen Sync Folder (pickSyncFolder()). Lives under Electron's
  // own app-data directory, never inside the user's visible Documents.
  getHiddenCloneDir: () => ipcRenderer.invoke('smartchef-get-hidden-clone-dir'),
  // Standalone-mode geocode proxy (RegionPicker.tsx's free-text regions) —
  // see the `smartchef-geocode` handler in electron/src/index.ts for why
  // this can't just be a renderer-side fetch() call.
  geocode: (q: string, limit?: number) => ipcRenderer.invoke('smartchef-geocode', q, limit),
  // Git Remote sync mode's HTTP transport — see the `smartchef-http-request`
  // handler in electron/src/index.ts for why this can't just be a
  // renderer-side fetch() call (same no-CORS-in-main-process reasoning as
  // geocode above).
  httpRequest: (req: { url: string; method: string; headers: Record<string, string>; body?: Uint8Array; timeoutMs?: number }) =>
    ipcRenderer.invoke('smartchef-http-request', req),
  fs: {
    readFile: (path: string, encoding?: string) => ipcRenderer.invoke('smartchef-fs-readFile', path, encoding),
    writeFile: (path: string, data: string | Uint8Array) => ipcRenderer.invoke('smartchef-fs-writeFile', path, data),
    unlink: (path: string) => ipcRenderer.invoke('smartchef-fs-unlink', path),
    readdir: (path: string) => ipcRenderer.invoke('smartchef-fs-readdir', path),
    mkdir: (path: string) => ipcRenderer.invoke('smartchef-fs-mkdir', path),
    rmdir: (path: string) => ipcRenderer.invoke('smartchef-fs-rmdir', path),
    stat: (path: string) => ipcRenderer.invoke('smartchef-fs-stat', path),
    rename: (oldPath: string, newPath: string) => ipcRenderer.invoke('smartchef-fs-rename', oldPath, newPath),
  },
});
